version: '3.8'
services:
 db:
    image: mysql:8
    volumes:
      - mysql-dev:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: users
      MYSQL_USER: admin
      MYSQL_PASSWORD: esteban123
      MYSQL_ROOT_PASSWORD: este5ban9
    ports:
      - 3306:3306
volumes:
  mysql-dev:
