services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"  
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    volumes:
      - mongodb_data:/data/db 

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongodb
    ports:
      - "8081:8081" 
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345678 
      ME_CONFIG_MONGODB_URL: mongodb://root:12345678@mongodb:27017/

volumes:
  mongodb_data:
    driver: local
